import Head from "next/head";
import Navbar from '../components/Navbar';
import SideOne from '../components/SideOne';
import SideTwo from '../components/SideTwo';
import Hero from '../components/Hero';
import About from '../components/About';
import Project from '../components/Project';
import {motion} from "framer-motion";


export default function Home() {
  return (
    <>
    <Head>
      <title>Portfolio</title>
      <meta name="desciption" content="Generated by Asrar Ali" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll">
       <Navbar />
       <div  className="w-full h-[88vh] xl flex items-center gap-20 justify-between">
        <motion.div
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{delay:1.5}}
        className="hidden xl:inline-flex w-32 ">
          < SideOne />
        </motion.div>
        <div className="h-[88vh] w-[660px] mx-auto p-4">
          < Hero />
          <About />
          <Project />
          {/* contact */}
          {/* footer */}
        </div>
        <div className="hidden lg:inline-flex w-full h-full top-0"> <SideTwo /> </div>
       </div>
    </main>
    </>
  );
}